### ISSUE TITLE
Logic for movie with Highest rating is InCorrect

### ISSUE THREAD

**Issue by ArjunReddyKorni** [Priyanka7775/mc-1-movie#1]
The logic written will not work properly. it will only check for movie with 5 rating.``

**Comment by ArjunReddyKorni** [comment]
`for (Map.Entry<Movie,Integer>integerEntry: map.entrySet()){
            if (integerEntry.getValue()==5){
                list.add(integerEntry.getKey().getMovieName());
            }
        }`

**Comment by Priyanka7775** [comment]
Made some changes and working properly.
